site_name: debian-gces-24.2
site_description: Documentação da disciplina de GCES 24.2 do grupo Debian

repo_name: debian-gces-24.2
repo_url: https://github.com/gitbmvb/debian-gces-24.2
site_url: https://github.com/gitbmvb/debian-gces-24.2

copyright: Copyright &copy; 2024 Debian GCES 24.2  

theme:
  name: material
  language: pt-BR
  logo: img/logo-debian.png
  favicon: img/icon-debian.png
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.action.edit
    - content.action.view
    - navigation.top
    - content.tabs.link
    - content.code.annotation
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Modo noturno
    - scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Modo claro

extra_css:
  - stylesheets/extra.css
extra:
  generator: false

nav:
  - Home: index.md
  - Sprint 1:
    - Planning da Sprint: sprint1/planning1.md
    - Ana Beatriz: sprint1/ana1.md
    - Bruno: sprint1/bruno1.md
    - Douglas: sprint1/douglas1.md
    - Geovanna: sprint1/geovanna1.md
    - João Lucas: sprint1/jl1.md
    - João Pedro: sprint1/jp1.md
    - Kauã: sprint1/kaua1.md
    - Luan: sprint1/luan1.md
    - Shaíne: sprint1/shaine1.md
  - Sprint 2:
    - Ana Beatriz: sprint2/ana2.md
    - Bruno: sprint2/bruno2.md
    - Douglas: sprint2/douglas2.md
    - Geovanna : sprint2/geovanna2.md
    - João Pedro: sprint2/jp2.md
    - Kauã: sprint2/kaua2.md
    - Luan: sprint2/luan2.md
    - Shaíne: sprint2/shaine2.md
  - Sprint 3:
    - Bruno: sprint3/bruno3.md
    - Douglas: sprint3/douglas3.md
    - Geovanna: sprint3/geovanna3.md
    - Kauã: sprint3/kaua3.md
    - Luan: sprint3/luan3.md
    - Shaine: sprint3/shaine3.md
